name: Build, Test, and Deploy .NET Application

on:
  push:
    branches:
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.403
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build Tic_Tac_Toe_Client.sln --configuration Release --property:Platform="x86"
        
      - name: Run tests
        run: dotnet test Tic_Tac_Toe_Client.sln --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"
      
      - name: Publish test reports as artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./TestResults/test_results.trx
          if-no-files-found: ignore

      - name: Publish build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: Tic_Tac_Toe_Client/bin/x86/Release/
          if-no-files-found: ignore
